# Generated by Django 4.2.23 on 2025-09-16 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, unique=True)),
                ("hex_code", models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("url", models.CharField(max_length=511)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_object", models.PositiveBigIntegerField(unique=True)),
                ("title", models.CharField(max_length=511)),
                ("image", models.URLField()),
                ("url", models.URLField(blank=True)),
                (
                    "image_local",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/%Y/%m/%d/"
                    ),
                ),
                ("is_man", models.BooleanField(blank=True, default=True, null=True)),
                ("age_group", models.CharField(blank=True, max_length=50, null=True)),
                ("skin_tone", models.CharField(blank=True, max_length=50, null=True)),
                ("hair_color", models.CharField(blank=True, max_length=50, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="styles",
                        to="get_data.site",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_man", models.BooleanField(blank=True, default=True, null=True)),
                ("title", models.CharField(max_length=511)),
                ("price", models.BigIntegerField()),
                ("image", models.URLField()),
                ("url", models.URLField(blank=True)),
                (
                    "image_local",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/%Y/%m/%d/"
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="get_data.site",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StylePredict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("image_embedding", models.JSONField(blank=True, null=True)),
                ("image_embedding_dim", models.IntegerField(blank=True, null=True)),
                (
                    "prediction_model",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("predicted_at", models.DateTimeField(blank=True, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="style_predicts", to="get_data.product"
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicts",
                        to="get_data.style",
                    ),
                ),
            ],
            options={
                "ordering": ["version"],
                "unique_together": {("style", "version")},
            },
        ),
        migrations.CreateModel(
            name="ProductPredict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField()),
                ("category_score", models.FloatField(blank=True, null=True)),
                ("color_score", models.FloatField(blank=True, null=True)),
                ("image_embedding", models.JSONField(blank=True, null=True)),
                ("image_embedding_dim", models.IntegerField(blank=True, null=True)),
                (
                    "classification_model",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("classified_at", models.DateTimeField(blank=True, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="get_data.category",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="get_data.color",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicts",
                        to="get_data.product",
                    ),
                ),
            ],
            options={
                "ordering": ["version"],
                "unique_together": {("product", "version")},
            },
        ),
    ]
