# Generated by Django 4.2.23 on 2025-09-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("get_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="style",
            name="weight",
        ),
        migrations.AddField(
            model_name="style",
            name="body_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
