# Generated by Django 4.2.23 on 2025-09-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("get_data", "0002_remove_style_weight_style_body_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="style",
            name="age_group",
        ),
        migrations.RemoveField(
            model_name="style",
            name="skin_tone",
        ),
        migrations.AddField(
            model_name="style",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="style",
            name="skin_color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="stylepredict",
            name="crop_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="style_crops/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="stylepredict",
            name="crop_meta",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="style",
            name="hair_color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
