# Generated by Django 4.2.23 on 2025-09-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("get_data", "0003_remove_style_age_group_remove_style_skin_tone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_local",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/none_group"
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="image_local",
            field=models.ImageField(blank=True, null=True, upload_to="styles/images"),
        ),
        migrations.AlterField(
            model_name="stylepredict",
            name="crop_image",
            field=models.ImageField(blank=True, null=True, upload_to="styles/crops"),
        ),
    ]
