# Generated by Django 4.2.23 on 2025-09-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("get_data", "0004_alter_product_image_local_alter_style_image_local_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stylepredict",
            unique_together=set(),
        ),
    ]
