# Generated by Django 4.2.23 on 2025-10-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("get_data", "0005_alter_stylepredict_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="stylepredict",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="style_predicts",
                to="get_data.category",
            ),
        ),
    ]
