# Generated by Django 4.2.23 on 2025-10-05 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("get_data", "0006_stylepredict_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="my_styles/images")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_styles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stylepredict",
            name="crop_name",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="style",
            name="id_object",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="stylepredict",
            name="prediction_model",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.CreateModel(
            name="MyStylePredict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=127)),
                (
                    "crop_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="my_styles/crops"
                    ),
                ),
                ("bounding_box", models.JSONField(blank=True, null=True)),
                ("image_embedding", models.JSONField(blank=True, null=True)),
                ("image_embedding_dim", models.IntegerField(blank=True, null=True)),
                (
                    "prediction_model",
                    models.CharField(blank=True, max_length=127, null=True),
                ),
                ("predict_elapsed", models.DurationField(blank=True, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="my_style_predicts",
                        to="get_data.category",
                    ),
                ),
                (
                    "detected_products",
                    models.ManyToManyField(
                        related_name="my_style_predicts", to="get_data.product"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="my_style_predicts_user",
                        to="get_data.product",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicts",
                        to="get_data.mystyle",
                    ),
                ),
            ],
        ),
    ]
