# Generated by Django 4.2.23 on 2025-10-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "get_data",
            "0007_mystyle_stylepredict_crop_name_alter_style_id_object_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mystylepredict",
            name="predict_elapsed",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
