# Generated by Django 4.2.23 on 2025-10-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "get_data",
            "0007_mystyle_stylepredict_crop_name_alter_style_id_object_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mystylepredict",
            unique_together={("bounding_box", "style")},
        ),
    ]
