# Generated by Django 4.2.23 on 2025-10-08 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("get_data", "0008_alter_mystylepredict_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mystyle",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_styles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
