# Generated by Django 4.2.23 on 2025-10-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("get_data", "0008_alter_mystylepredict_predict_elapsed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mystylepredict",
            old_name="crop_meta",
            new_name="bounding_box",
        ),
    ]
