# Generated by Django 4.2.23 on 2025-10-15 17:29

from django.db import migrations, models
import get_data.models


class Migration(migrations.Migration):

    dependencies = [
        ("get_data", "0009_alter_mystyle_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="style",
            name="image_local",
            field=models.ImageField(
                blank=True, null=True, upload_to=get_data.models.style_crop_upload_path
            ),
        ),
    ]
