# Generated by Django 4.2.23 on 2025-12-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("get_data", "0011_alter_style_image_local_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mystylepredict",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_styles",
                to="get_data.color",
            ),
        ),
        migrations.AddField(
            model_name="mystylepredict",
            name="color_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stylepredict",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="styles",
                to="get_data.color",
            ),
        ),
        migrations.AddField(
            model_name="stylepredict",
            name="color_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
