# Generated by Django 4.2.23 on 2026-01-03 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("get_data", "0012_mystylepredict_color_mystylepredict_color_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mystyle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
