# Generated by Django 4.2.23 on 2025-10-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_day",
            field=models.DateField(blank=True, help_text="تاریخ تولد", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="image_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
