# Generated by Django 4.2.23 on 2025-10-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_image_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
