# Generated by Django 4.2.23 on 2025-10-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_image_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_show",
            field=models.BooleanField(default=True),
        ),
    ]
